# Generated by Django 3.1.7 on 2021-04-23 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Range 5 - 5000', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='MM/DD/YYYY'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_age',
            field=models.PositiveIntegerField(default=70, help_text='Maximum 70', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(70)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_age',
            field=models.PositiveIntegerField(default=5, help_text='Minimum 5', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(70)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Enter the name of your event', max_length=100),
        ),
    ]
