# Generated by Django 3.1.7 on 2021-03-16 23:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetup', '0002_auto_20210316_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetupuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='meetupuser',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='meetupuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.meetupuser')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('price', models.PositiveIntegerField(default=0)),
                ('max_age', models.PositiveIntegerField(default=100)),
                ('min_age', models.PositiveIntegerField(default=0)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('activity_type', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('contact_info', models.TextField()),
                ('attendees', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.meetupuser')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999)])),
                ('expiry_date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('cvc_code', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup.meetupuser')),
            ],
        ),
    ]
