# Generated by Django 3.1.7 on 2021-04-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0005_auto_20210410_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigIntegerField(default=-919057513908289055, primary_key=True, serialize=False),
        ),
    ]
