# Generated by Django 3.1.7 on 2021-03-18 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0007_auto_20210317_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='credit_card_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(16), django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cvc_code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(3), django.core.validators.MinLengthValidator(3)]),
        ),
    ]
