# Generated by Django 3.1.7 on 2021-04-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup', '0008_auto_20210416_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
